import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Router from 'next/router'
import * as React from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const connectWallet = async () => {
    try{
      const { ethereum } = window
      if(!ethereum){
        alert("Get MetaMask!")
        return
      }
      const address = await ethereum.request({ method: 'eth_requestAccounts' })
      console.log(address)
      localStorage.setItem('address', address[0])
      Router.push('/dashboard')
    }
    catch(err){
      console.log(err)
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={connectWallet} className={styles.btn}>Connect Your Wallet</button>
      </main>
    </>
  )
}
